# -*- coding: utf-8 -*-
"""Arcade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V4y9qXlASzxwPvLXRPyHzTOK7hgy0QwM
"""

import random

def mostrar_menu():
    print("\n MINI ARCADE – MENÚ PRINCIPAL")
    print("1. Adivina el número")
    print("2. Par o impar")
    print("3. Cara o sello")
    print("4. Piedra, papel o tijera")
    print("5. Ruleta 1-5")
    print("6. Salir\n")

# ------------------------------
# Juego 1: Adivina el número
# ------------------------------
def adivina_numero():
    numero_secreto = random.randint(1, 10)
    intentos = 0
    print("\n Adivina el número entre 1 y 10")

    while True:
        try:
            intento = int(input("Escribe tu número: "))
            intentos += 1

            if intento < numero_secreto:
                print("Muy bajo ⬇")
            elif intento > numero_secreto:
                print("Muy alto ⬆")
            else:
                print(f" ¡Correcto! El número era {numero_secreto}. Intentos: {intentos}")
                break
        except ValueError:
            print("Por favor escribe un número válido.")

# ------------------------------
# Juego 2: Par o impar
# ------------------------------
def par_o_impar():
    print("\n PAR O IMPAR")
    eleccion = input("¿Crees que será par o impar? ").lower()

    if eleccion not in ["par", "impar"]:
        print("Opción inválida")
        return

    numero = random.randint(1, 20)
    resultado = "par" if numero % 2 == 0 else "impar"

    print(f"El número generado fue {numero} → {resultado}")
    if resultado == eleccion:
        print(" ¡Ganaste!")
    else:
        print(" Perdiste")

# ------------------------------
# Juego 3: Cara o sello
# ------------------------------
def cara_o_sello():
    print("\ CARA O SELLO")
    eleccion = input("Elige 'cara' o 'sello': ").lower()

    if eleccion not in ["cara", "sello"]:
        print(" Opción inválida")
        return

    resultado = random.choice(["cara", "sello"])
    print(f"La moneda cayó en: {resultado}")

    if eleccion == resultado:
        print(" ¡Ganaste!")
    else:
        print(" Perdiste")

# ------------------------------
# Juego 4: Piedra, papel o tijera
# ------------------------------
def piedra_papel_tijera():
    print("\n PIEDRA, PAPEL O TIJERA")
    usuario = input("Elige piedra, papel o tijera: ").lower()
    opciones = ["piedra", "papel", "tijera"]

    if usuario not in opciones:
        print("Opción inválida")
        return

    maquina = random.choice(opciones)
    print(f"La máquina eligió: {maquina}")

    if usuario == maquina:
        print(" Empate")
    elif (
        (usuario == "piedra" and maquina == "tijera") or
        (usuario == "tijera" and maquina == "papel") or
        (usuario == "papel" and maquina == "piedra")
    ):
        print(" ¡Ganaste!")
    else:
        print(" Perdiste")

# ------------------------------
# Juego 5: Ruleta 1-5
# ------------------------------
def ruleta():
    print("\n RULETA 1-5")
    try:
        numero = int(input("Elige un número del 1 al 5: "))
        if numero < 1 or numero > 5:
            print(" Debes elegir entre 1 y 5")
            return
    except ValueError:
        print(" Ingresa un número válido")
        return

    resultado = random.randint(1, 5)
    print(f"La ruleta cayó en: {resultado}")

    if numero == resultado:
        print(" ¡Ganaste!")
    else:
        print(" Perdiste")

# ------------------------------
# Programa principal
# ------------------------------
def main():
    while True:
        mostrar_menu()
        opcion = input("Selecciona una opción: ")

        if opcion == "1":
            adivina_numero()
        elif opcion == "2":
            par_o_impar()
        elif opcion == "3":
            cara_o_sello()
        elif opcion == "4":
            piedra_papel_tijera()
        elif opcion == "5":
            ruleta()
        elif opcion == "6":
            print("\n Gracias por jugar. ¡Hasta pronto!")
            break
        else:
            print(" Opción inválida, intenta nuevamente.")

if __name__ == "__main__":
    main()